#!/usr/bin/env bash
./generate
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./css ./fonts ./img ./js ./index.html \
  pixelastic:/var/www/talks.pixelastic.com/slides/vim-syntastic
